import os

TWITTER_TWEET_LIMIT = 140

TLKSIO_TWITTER_TOKEN = os.environ['TLKSIO_TWITTER_TOKEN'] or ""
TLKSIO_TWITTER_SECRET = os.environ['TLKSIO_TWITTER_SECRET'] or ""
TLKSIO_TWITTER_ACCESS_TOKEN = os.environ['TLKSIO_TWITTER_ACCESS_TOKEN'] or ""
TLKSIO_TWITTER_ACCESS_SECRET = os.environ['TLKSIO_TWITTER_ACCESS_SECRET'] or ""

VTALKS_API_RANDOM_TALK_URL = 'https://vtalks.net/api/random-talk/'
