import json

fake_talk_json = json.loads("""{
    "id": 3637,
    "code": "2nQMwvW4buU",
    "title": "Josh McClain: Black Magic APIs [JSConf2014]",
    "slug": "josh-mcclain-black-magic-apis-jsconf2014",
    "description": "This talk is about my deliberate choice to try writing a Node.js ORM with no respect for simplicity, maintainability, or goodwill towards mankind -- but that reads like a dream.",
    "duration": "00:27:45",
    "youtube_url": "https://www.youtube.com/watch?v=2nQMwvW4buU",
    "default_thumb": "https://i.ytimg.com/vi/2nQMwvW4buU/default.jpg",
    "medium_thumb": "https://i.ytimg.com/vi/2nQMwvW4buU/mqdefault.jpg",
    "high_thumb": "https://i.ytimg.com/vi/2nQMwvW4buU/hqdefault.jpg",
    "standard_thumb": "https://i.ytimg.com/vi/2nQMwvW4buU/sddefault.jpg",
    "maxres_thumb": "https://i.ytimg.com/vi/2nQMwvW4buU/maxresdefault.jpg",
    "view_count": 0,
    "like_count": 0,
    "dislike_count": 0,
    "favorite_count": 0,
    "youtube_view_count": 1346,
    "youtube_like_count": 11,
    "youtube_dislike_count": 4,
    "youtube_favorite_count": 0,
    "total_view_count": 1346,
    "total_like_count": 11,
    "total_dislike_count": 4,
    "total_favorite_count": 0,
    "wilsonscore_rank": 0.480491103423132,
    "hacker_hot": 7.85188310909664e-05,
    "tags": [
        "jsconf",
        "JSConf2014",
        "Josh McClain"
    ],
    "created": "2014-07-17T16:29:08+02:00",
    "updated": "2018-02-24T13:23:53.857834+01:00",
    "channel": 27,
    "playlist": 61,
    "event_edition": null
}""")